### ISSUE TITLE
Please add pypi package

### ISSUE THREAD

**Issue by HanzCEO** [renatoliveira/midd#1]
I need to use this script in many devices and yeah that will be great if you provide a pypi package

**Comment by renatoliveira** [comment]
I can try and read on how to provide this as a package in PyPi later today. I just hope you are not in a hurry to get it. 

Meanwhile you can download this repository and manually add it to your project.

**Comment by HanzCEO** [comment]
thanks for fast respond, FYI im not in hurry

**Comment by HanzCEO** [comment]
btw, can i use `../example` in `--directory`?

**Comment by renatoliveira** [comment]
> btw, can i use `../example` in `--directory`?

It has been a while since I've touched the code, but I suppose you can. That argument specifies a directory path. As long as it points to a directory containing the images you should be fine using it.

**Comment by renatoliveira** [comment]
@HanzHaxors you can install the package through PyPI now, see: https://pypi.org/project/midd/1.1.2

**Comment by HanzCEO** [comment]
Thank you!
